apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ecommerce-api

  template:
    metadata:
      labels:
        app: ecommerce-api

    spec:
      containers:
        - name: ecommerce-api
          image: ecommerce-api:local
          ports:
            - containerPort: 5000