name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Show project files
        run: ls -la

      - name: Build Docker image
        run: docker build -t ecommerce-api:ci .

      - name: Run Docker container
        run: docker run -d --name ecommerce-api -p 5000:5000 ecommerce-api:ci

      - name: Test API health
        run: curl --fail http://localhost:5000/health

      - name: Stop Docker container
        if: always()
        run: docker stop ecommerce-api
