name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Show project files
        run: ls -la

      - name: Run basic test
        run: echo "CI test passed!"